FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY storage_client.py .
COPY mongo_client.py .
COPY init_storage.py .
COPY storage_api.py .

EXPOSE 5003

CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:5003", "storage_api:app"]
